[AD-1] - Deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,15 +24,18 @@ jobs:
 
       - name: Check Deployment Image Version
         run: |
-          git pull origin CA-9:CA-9
+          git pull origin ${{ github.event.base_ref }}
 
           IMAGE_VERSION=$(cat .k8s/${{ env.ENVIRONMENT }}/deployment.yml | awk "/image:/ {print $2}" | sed "s/.*.cart-api.//")
 
+          if [[ $IMAGE_VERSION == ${{ github.ref_name }} ]]; then
+            echo "==== Ok"
+          else
+            echo "==== Error: Image version is different from tag."
+            exit 1
+          fi
+
           echo "--------------"
-          echo $IMAGE_VERSION
-          echo ${{ github.ref_name }}
-          echo ${{ github.base_ref }}
-          echo ${{ github.event.ref_name }}
           echo ${{ github.event.base_ref }}
           echo "--------------"
 
