[AD-1] - Deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,8 +27,20 @@ jobs:
           git pull origin CA-9:CA-9
 
           IMAGE_VERSION=$(cat .k8s/${{ env.ENVIRONMENT }}/deployment.yml | awk "/image:/ {print $2}" | sed "s/.*.cart-api.//")
-          
-          echo "------------"
-          echo $IMAGE_VERSION
-          echo "------------"
+
+          if [[ $IMAGE_VERSION == ${{ github.ref_name }} ]]; then
+            echo "==== Ok"
+          else
+            echo "==== Error: Image version is different from tag."
+            exit 1
+          fi
+
+      - name: Test
+        run: |
+          echo "--------------"
+          echo ${{ github.ref_name }}
+          echo ${{ github.base_ref }}
+          echo ${{ github.event.ref_name }}
+          echo ${{ github.event.base_ref }}
+          echo "--------------"
 
